[DEFAULT]
AppName = Gomokuapp
#Version = 1.0.0

[Settings]
theme = light
auto_save = True

[Folders]
replay_folder = ".\test_situations\specific_situation.txt"

[UI]
width = 800
height = 600
distance_from_left_side = 10

[GAME]
board_size = 15